---
title: "Project 1 Goup E XML"
author: "Phillip Rodriguez-Lebron"
date: "6/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, message = FALSE, warning = FALSE}

library(xml2)
library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)

```

```{r dataset table}

xml <- read_xml("http://www.ggobi.org/book/data/australian-crabs.xml")

records <- xml_find_all(xml, "//record")

text <- xml_text(records)
text <- str_remove_all(text, "[\n]")
text <- text[-c(201:208)]


getTable <- function(x){

  split <- strsplit(x[1:200], " ")
  
  split.df <- data.frame(matrix(unlist(split), nrow = length(split), byrow = TRUE),                   stringsAsFactors = FALSE)
  
  split.tbl <- tbl_df(split.df)
  
  a <- split.tbl %>% rename(Species = X1, Sex = X2, Index = X3, "Frontal Lip" = X4,
                     "Rear Width" = X5, "Carapace Length" = X6, "Carapace Width" = X7,                       "Body Depth" = X8) %>% mutate(Species = as.factor(Species), 
                     Sex = as.factor(Sex)) %>% mutate_if(is.character, as.numeric) %>%
                     mutate(Species = recode(Species, "0" = "Blue",  "1" = "Orange")) %>%  mutate(Sex = recode(Sex, "0" = "Male", "1" = "Female"))
  
  return(a)

}

crab.table <- getTable(text)

```

```{r contingency table}

small <- quantile(crab.table$`Body Depth`, 0.25)
large <- quantile(crab.table$`Body Depth`, 0.75)

getBodyDepth <- function(x){
  
  ifelse(x < small, "Small", ifelse((x >= small) & (x <= large), "Medium", "Large"))
  
}

change <- crab.table %>% mutate(`Body Depth` = getBodyDepth(`Body Depth`))

table(change$Sex, change$`Body Depth`) %>% kable(caption = "The Sex of Crabs by Body Depth") %>% kable_styling()

```